// Canonical Melbourne coverage-zone mapping shared by lifecycle automation.
const CONTRACTOR_REGIONS = ['Northern Melbourne', 'Western Melbourne', 'Inner/CBD Melbourne', 'Southern Melbourne', 'Eastern Melbourne'];
const SUBURB_TO_REGION = {
  'coburg':'Northern Melbourne','preston':'Northern Melbourne','reservoir':'Northern Melbourne','thornbury':'Northern Melbourne','northcote':'Northern Melbourne','fairfield':'Northern Melbourne','alphington':'Northern Melbourne','ivanhoe':'Northern Melbourne','heidelberg':'Northern Melbourne','bundoora':'Northern Melbourne','mill park':'Northern Melbourne','epping':'Northern Melbourne','south morang':'Northern Melbourne','whittlesea':'Northern Melbourne','craigieburn':'Northern Melbourne','broadmeadows':'Northern Melbourne','fawkner':'Northern Melbourne','brunswick':'Northern Melbourne','brunswick east':'Northern Melbourne','brunswick west':'Northern Melbourne','pascoe vale':'Northern Melbourne','glenroy':'Northern Melbourne','tullamarine':'Northern Melbourne','greenvale':'Northern Melbourne','roxburgh park':'Northern Melbourne','campbellfield':'Northern Melbourne','thomastown':'Northern Melbourne','lalor':'Northern Melbourne','watsonia':'Northern Melbourne','greensborough':'Northern Melbourne','eltham':'Northern Melbourne','diamond creek':'Northern Melbourne','doreen':'Northern Melbourne','kingsbury':'Northern Melbourne','macleod':'Northern Melbourne','yallambie':'Northern Melbourne',
  'frankston':'Southern Melbourne','dandenong':'Southern Melbourne','cranbourne':'Southern Melbourne','mordialloc':'Southern Melbourne','chelsea':'Southern Melbourne','carrum':'Southern Melbourne','bentleigh':'Southern Melbourne','bentleigh east':'Southern Melbourne','cheltenham':'Southern Melbourne','moorabbin':'Southern Melbourne','brighton':'Southern Melbourne','sandringham':'Southern Melbourne','hampton':'Southern Melbourne','mentone':'Southern Melbourne','parkdale':'Southern Melbourne','aspendale':'Southern Melbourne','edithvale':'Southern Melbourne','seaford':'Southern Melbourne','langwarrin':'Southern Melbourne','skye':'Southern Melbourne','berwick':'Southern Melbourne','narre warren':'Southern Melbourne','pakenham':'Southern Melbourne','officer':'Southern Melbourne','hallam':'Southern Melbourne','clayton':'Southern Melbourne','springvale':'Southern Melbourne','noble park':'Southern Melbourne','keysborough':'Southern Melbourne','doveton':'Southern Melbourne','endeavour hills':'Southern Melbourne','hastings':'Southern Melbourne','mornington':'Southern Melbourne','mount eliza':'Southern Melbourne','somerville':'Southern Melbourne','rosebud':'Southern Melbourne','carnegie':'Southern Melbourne','murrumbeena':'Southern Melbourne','hughesdale':'Southern Melbourne','ormond':'Southern Melbourne','mckinnon':'Southern Melbourne','elwood':'Southern Melbourne',
  'box hill':'Eastern Melbourne','camberwell':'Eastern Melbourne','hawthorn':'Eastern Melbourne','kew':'Eastern Melbourne','balwyn':'Eastern Melbourne','doncaster':'Eastern Melbourne','templestowe':'Eastern Melbourne','ringwood':'Eastern Melbourne','croydon':'Eastern Melbourne','bayswater':'Eastern Melbourne','boronia':'Eastern Melbourne','ferntree gully':'Eastern Melbourne','knox':'Eastern Melbourne','wantirna':'Eastern Melbourne','vermont':'Eastern Melbourne','mitcham':'Eastern Melbourne','blackburn':'Eastern Melbourne','nunawading':'Eastern Melbourne','glen waverley':'Eastern Melbourne','mount waverley':'Eastern Melbourne','ashburton':'Eastern Melbourne','ashwood':'Eastern Melbourne','chadstone':'Eastern Melbourne','oakleigh':'Eastern Melbourne','malvern':'Eastern Melbourne','malvern east':'Eastern Melbourne','armadale':'Eastern Melbourne','toorak':'Eastern Melbourne','canterbury':'Eastern Melbourne','surrey hills':'Eastern Melbourne','mont albert':'Eastern Melbourne','burwood':'Eastern Melbourne','forest hill':'Eastern Melbourne','heathmont':'Eastern Melbourne','belgrave':'Eastern Melbourne','upwey':'Eastern Melbourne','lilydale':'Eastern Melbourne','mooroolbark':'Eastern Melbourne','chirnside park':'Eastern Melbourne','warrandyte':'Eastern Melbourne','rowville':'Eastern Melbourne','scoresby':'Eastern Melbourne','bayswater north':'Eastern Melbourne',
  'footscray':'Western Melbourne','yarraville':'Western Melbourne','seddon':'Western Melbourne','kingsville':'Western Melbourne','williamstown':'Western Melbourne','newport':'Western Melbourne','spotswood':'Western Melbourne','altona':'Western Melbourne','altona north':'Western Melbourne','laverton':'Western Melbourne','point cook':'Western Melbourne','werribee':'Western Melbourne','hoppers crossing':'Western Melbourne','tarneit':'Western Melbourne','truganina':'Western Melbourne','sunshine':'Western Melbourne','sunshine west':'Western Melbourne','braybrook':'Western Melbourne','deer park':'Western Melbourne','caroline springs':'Western Melbourne','melton':'Western Melbourne','bacchus marsh':'Western Melbourne','st albans':'Western Melbourne','keilor':'Western Melbourne','keilor east':'Western Melbourne','keilor downs':'Western Melbourne','sydenham':'Western Melbourne','taylors lakes':'Western Melbourne','delahey':'Western Melbourne','ardeer':'Western Melbourne','albion':'Western Melbourne','maidstone':'Western Melbourne','maribyrnong':'Western Melbourne','west footscray':'Western Melbourne','tottenham':'Western Melbourne',
  'melbourne':'Inner/CBD Melbourne','melbourne cbd':'Inner/CBD Melbourne','southbank':'Inner/CBD Melbourne','docklands':'Inner/CBD Melbourne','south yarra':'Inner/CBD Melbourne','prahran':'Inner/CBD Melbourne','windsor':'Inner/CBD Melbourne','st kilda':'Inner/CBD Melbourne','st kilda east':'Inner/CBD Melbourne','balaclava':'Inner/CBD Melbourne','richmond':'Inner/CBD Melbourne','cremorne':'Inner/CBD Melbourne','abbotsford':'Inner/CBD Melbourne','collingwood':'Inner/CBD Melbourne','fitzroy':'Inner/CBD Melbourne','fitzroy north':'Inner/CBD Melbourne','carlton':'Inner/CBD Melbourne','carlton north':'Inner/CBD Melbourne','parkville':'Inner/CBD Melbourne','north melbourne':'Inner/CBD Melbourne','west melbourne':'Inner/CBD Melbourne','east melbourne':'Inner/CBD Melbourne','flemington':'Inner/CBD Melbourne','kensington':'Inner/CBD Melbourne','south melbourne':'Inner/CBD Melbourne','port melbourne':'Inner/CBD Melbourne','albert park':'Inner/CBD Melbourne','middle park':'Inner/CBD Melbourne',
};
function suburbToRegion(suburb) {
  if (!suburb) return null;
  const key = String(suburb).toLowerCase().trim();
  if (SUBURB_TO_REGION[key]) return SUBURB_TO_REGION[key];
  for (const s in SUBURB_TO_REGION) {
    if (key.includes(s)) return SUBURB_TO_REGION[s];
  }
  return null;
}
function jobMatchesContractorArea(jobSuburb, application) {
  const regions = (application && application.regions) || [];
  if (!jobSuburb) return true;
  const jobSuburbLower = String(jobSuburb).toLowerCase();
  const freeSuburbs = ((application && application.suburbs) || []).filter(s => !CONTRACTOR_REGIONS.includes(s));
  if (!regions.length && !freeSuburbs.length) return true;
  if (freeSuburbs.some(s => { const sl = String(s).toLowerCase().trim(); return sl && (jobSuburbLower.includes(sl) || sl.includes(jobSuburbLower)); })) return true;
  const jobRegion = suburbToRegion(jobSuburb);
  if (!jobRegion) return regions.length > 0;
  return regions.includes(jobRegion);
}

module.exports = { CONTRACTOR_REGIONS, suburbToRegion, jobMatchesContractorArea };
