const { getSupabase }=require('./_lib/clients'); const { requireAdmin }=require('./_lib/adminAuth');
function clean(v,n){return String(v||'').trim().slice(0,n||30000)}
function slug(v){return clean(v,180).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
module.exports=async function handler(req,res){if(!requireAdmin(req,res))return;const s=getSupabase();try{
 const action=clean((req.query&&req.query.action)||(req.body&&req.body.action),50);
 if(req.method==='GET'&&action==='list'){const {data,error}=await s.from('blog_posts').select('*').order('updated_at',{ascending:false}).limit(500);if(error)throw error;res.status(200).json({posts:data||[]});return;}
 if(req.method==='POST'&&action==='save'){const b=req.body||{},id=clean(b.id,50);const row={title:clean(b.title,240),slug:slug(b.slug||b.title),seo_title:clean(b.seoTitle,240)||null,meta_description:clean(b.metaDescription,500)||null,target_keywords:clean(b.targetKeywords,1000)||null,excerpt:clean(b.excerpt,1500)||null,body_html:clean(b.bodyHtml,30000)||null,feature_image_url:clean(b.featureImageUrl,1500)||null,feature_image_alt:clean(b.featureImageAlt,300)||null,status:['draft','ready_for_review','approved','scheduled','archived'].includes(b.status)?b.status:'draft',scheduled_for:b.scheduledFor||null,updated_at:new Date().toISOString()};if(!row.title||!row.slug){res.status(400).json({error:'Title and slug are required.'});return;}const q=id?s.from('blog_posts').update(row).eq('id',id):s.from('blog_posts').insert(row);const {data,error}=await q.select('*').single();if(error)throw error;res.status(id?200:201).json({post:data});return;}
 if(req.method==='POST'&&action==='approve'){const id=clean(req.body&&req.body.id,50);const {data,error}=await s.from('blog_posts').update({status:'approved',updated_at:new Date().toISOString()}).eq('id',id).select('*').single();if(error)throw error;res.status(200).json({post:data});return;}
 if(req.method==='POST'&&action==='publish'){const id=clean(req.body&&req.body.id,50);const {data:existing,error:x}=await s.from('blog_posts').select('id,status').eq('id',id).maybeSingle();if(x)throw x;if(!existing||existing.status!=='approved'){res.status(409).json({error:'Article must be approved before publishing.'});return;}const now=new Date().toISOString();const {data,error}=await s.from('blog_posts').update({status:'published',published_at:now,updated_at:now}).eq('id',id).select('*').single();if(error)throw error;res.status(200).json({post:data});return;}
 res.status(400).json({error:'Unsupported Blog and SEO action.'});
}catch(e){console.error('blog seo error',e);res.status(500).json({error:'Blog and SEO request failed.'});}};